version: '3.8'

services:
  speech-to-text:
    build: .
    container_name: speech-to-text-app
    devices:
      - /dev/snd:/dev/snd  # Audio device passthrough
    environment:
      - SPEAKERBOT_WEBSOCKET_URL=${SPEAKERBOT_WEBSOCKET_URL:-ws://host.docker.internal:8080}
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}
      - CHUNK_DURATION=${CHUNK_DURATION:-3.0}
      - SILENCE_THRESHOLD=${SILENCE_THRESHOLD:-0.01}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    restart: unless-stopped
